### ISSUE TITLE
SVG's in IE8 positioning of the SVG does not position itself correctly. 

### ISSUE THREAD

**Issue by code-mattclaffey** [code-computerlove/slate#13]
I am working on a project at the minute where the background positioning on SVG's display incorrectly. I am using the mixin *old-ie8-scaled-svg* but it renders out like this: (see attached). I have also attached the css code in IE8 for a specific svg. This could be a case of incorrect implementation or a bug so I have labelled this as help wanted for now. 

![screen shot 2016-01-07 at 13 58 15](https://cloud.githubusercontent.com/assets/10598938/12172091/a9e8161a-b546-11e5-8488-be72ba1307ef.png)
![screen shot 2016-01-07 at 13 57 59](https://cloud.githubusercontent.com/assets/10598938/12172092/ae0a0fb4-b546-11e5-8c8f-e2994fdfd354.png)

**Comment by code-mattclaffey** [comment]
Spoke to Darren this morning and the issue is to do with the font size. Font size had to be set to 16px.

**Comment by tawashley** [comment]
@code-mattclaffey Can this issue be closed?
